In [2]:
import pandas as pd
from time import strftime

filename = input('Enter full file name: ')
df = pd.read_csv(filename)

df = df[df['Type'] == 'Sent']

rests = ['Shaikpet', 'Kondapur', 'Yousufguda', 'Gachibowli', 'Istahgrill Himayat Nagar', 'Madhapur']
sales = {}
consumption = {}
raw_materials = []
for rest in rests:
    temp_df = df[df['To outlet'] == rest]
    if (len(temp_df.index) != 0):
        start_date = pd.to_datetime(min(temp_df['Created at'])).strftime('%d-%m-%Y')
        end_date = pd.to_datetime(max(temp_df['Created at'])).strftime('%d-%m-%Y')
        sales[rest] = int(input('Enter sale for {} from {} to {} from Sales Sheet is: '.format(rest, start_date, end_date)))
        rest_consumption = {}
        for item in temp_df['Items']:
            entities = item.split('; ')
            for entity in entities:
                split = entity.split(' - ')
                item_name = split[0]
                if item_name not in raw_materials:
                    raw_materials.append(item_name)
                item_qty = float(split[1])
                if item_name in rest_consumption.keys():
                    rest_consumption[item_name] += item_qty
                else:
                    rest_consumption[item_name] = item_qty
        consumption[rest] = rest_consumption
    else:
        print('No sent report found for {} from {} to {}'.format(rest, start_date, end_date))
    

raw_materials_cost = {
    'UN COOKED CHICKEN': 250,
    'PANEER': 220,
    'BASE SAUCE': 94.05,
    'HUMMUS': 93,
    'GREEN CHILLY': 75,
    'RUMALI': 5.5,
    'KHUBUS': 35,
    'CHEESE POPPERS': 365,
    'FRENCH FRIES': 270,
    'EGGS': 5,
    'HONEY MUSTARD': 172,
    'MINT MAYO': 172,
    'FALAFEL': 30,
    'OIL TIN': 1410
}

print()
print('Cost of raw materials: {}'.format(raw_materials_cost))

food_cost = {}
for rest, rest_consumption in consumption.items():
    cost = 0
    for raw_material, qty in rest_consumption.items():
        cost += raw_materials_cost[raw_material]*qty
    food_cost[rest] = cost

food_cost_precentage = {}

for rest, cost in food_cost.items():
    if sales[rest] != 0:
        food_cost_precentage[rest] = round((cost*100)/sales[rest], 1)
    else:
        food_cost_precentage[rest] = 0

print()
print('=== RESULTS ===')
print("Outlet wise sales from {} to {}:".format(start_date, end_date))
for i,v in sales.items():
    print('{}: {}'.format(i,v))
print()
print("Outlet wise food cost from {} to {}:".format(start_date, end_date))
for i,v in food_cost.items():
    print('{}: {}'.format(i,v))
print()
print("Outlet Wise food cost percentage from {} to {}".format(start_date, end_date))
for i,v in food_cost_precentage.items():
    print('{}: {}%'.format(i,v))

Enter full file name: outlet-orders-2019-03-16.csv
Enter sale for Shaikpet from 01-03-2019 to 15-03-2019 from Sales Sheet is: 290961
Enter sale for Kondapur from 01-03-2019 to 15-03-2019 from Sales Sheet is: 618035
Enter sale for Yousufguda from 01-03-2019 to 15-03-2019 from Sales Sheet is: 501441
Enter sale for Gachibowli from 01-03-2019 to 15-03-2019 from Sales Sheet is: 635527
Enter sale for Istahgrill Himayat Nagar from 01-03-2019 to 15-03-2019 from Sales Sheet is: 371077
Enter sale for Madhapur from 01-03-2019 to 15-03-2019 from Sales Sheet is: 802646

Cost of raw materials: {'UN COOKED CHICKEN': 250, 'PANEER': 220, 'BASE SAUCE': 94.05, 'HUMMUS': 93, 'GREEN CHILLY': 75, 'RUMALI': 5.5, 'KHUBUS': 35, 'CHEESE POPPERS': 365, 'FRENCH FRIES': 270, 'EGGS': 5, 'HONEY MUSTARD': 172, 'MINT MAYO': 172, 'FALAFEL': 30, 'OIL TIN': 1410}

=== RESULTS ===
Outlet wise sales from 01-03-2019 to 15-03-2019:
Shaikpet: 290961
Kondapur: 618035
Yousufguda: 501441
Gachibowli: 635527
Istahgrill Himayat Nagar: 371077
Madhapur: 802646

Outlet wise food cost from 01-03-2019 to 15-03-2019:
Shaikpet: 95361.35
Kondapur: 231875.7
Yousufguda: 173744.9
Gachibowli: 191657.95
Istahgrill Himayat Nagar: 150408.5
Madhapur: 219105.75

Outlet Wise food cost percentage from 01-03-2019 to 15-03-2019
Shaikpet: 32.8%
Kondapur: 37.5%
Yousufguda: 34.6%
Gachibowli: 30.2%
Istahgrill Himayat Nagar: 40.5%
Madhapur: 27.3%

In [21]:
cons = pd.DataFrame(consumption)
cons

,Shaikpet,Kondapur,Yousufguda,Gachibowli,Istahgrill Himayat Nagar,Madhapur
BASE SAUCE,47.0,114.0,98.0,99.0,90.0,105.0
CHEESE POPPERS,7.0,11.0,6.0,13.0,6.0,4.0
EGGS,420.0,750.0,750.0,920.0,795.0,60.0
FALAFEL,16.0,41.0,24.0,34.0,19.0,20.0
FRENCH FRIES,10.0,26.0,22.0,34.0,21.0,6.0
GREEN CHILLY,11.0,40.0,59.0,31.0,7.0,21.0
HONEY MUSTARD,2.0,9.0,8.0,5.0,2.0,3.0
HUMMUS,29.0,75.0,55.0,64.0,41.0,79.0
KHUBUS,138.0,274.0,202.0,231.0,171.0,238.0
MINT MAYO,NaN,3.0,1.0,NaN,1.0,1.0
OIL TIN,5.0,12.0,8.0,12.0,8.0,1.0
PANEER,16.0,43.0,29.0,31.0,30.0,33.0
RUMALI,1380.0,2660.0,2020.0,2380.0,1740.0,3571.0
UN COOKED CHICKEN,225.0,570.0,420.0,435.0,365.0,636.0

In [22]:
pd.Series(raw_materials_cost)

UN COOKED CHICKEN     250.00
PANEER                220.00
BASE SAUCE             94.05
HUMMUS                 93.00
GREEN CHILLY           75.00
RUMALI                  5.50
KHUBUS                 35.00
CHEESE POPPERS        365.00
FRENCH FRIES          270.00
EGGS                    5.00
HONEY MUSTARD         172.00
MINT MAYO             172.00
FALAFEL                30.00
OIL TIN              1410.00
dtype: float64

In [23]:
cons.multiply(pd.Series(raw_materials_cost), axis='index')

,Shaikpet,Kondapur,Yousufguda,Gachibowli,Istahgrill Himayat Nagar,Madhapur
BASE SAUCE,4420.35,10721.7,9216.9,9310.95,8464.5,9875.25
CHEESE POPPERS,2555.00,4015.0,2190.0,4745.00,2190.0,1460.00
EGGS,2100.00,3750.0,3750.0,4600.00,3975.0,300.00
FALAFEL,480.00,1230.0,720.0,1020.00,570.0,600.00
FRENCH FRIES,2700.00,7020.0,5940.0,9180.00,5670.0,1620.00
GREEN CHILLY,825.00,3000.0,4425.0,2325.00,525.0,1575.00
HONEY MUSTARD,344.00,1548.0,1376.0,860.00,344.0,516.00
HUMMUS,2697.00,6975.0,5115.0,5952.00,3813.0,7347.00
KHUBUS,4830.00,9590.0,7070.0,8085.00,5985.0,8330.00
MINT MAYO,NaN,516.0,172.0,NaN,172.0,172.00
OIL TIN,7050.00,16920.0,11280.0,16920.00,11280.0,1410.00
PANEER,3520.00,9460.0,6380.0,6820.00,6600.0,7260.00
RUMALI,7590.00,14630.0,11110.0,13090.00,9570.0,19640.50
UN COOKED CHICKEN,56250.00,142500.0,105000.0,108750.00,91250.0,159000.00